### ISSUE TITLE
Switch to Persian!

### ISSUE THREAD

**Issue by farooqkz** [rsharifnasab/my-learning#1]
فارسی بنویسید بجای انگلیسی. در فارسی اینجور چیز‌ها را کم داریم و فارسی زبانان مجبورند انگلیسی یاد بگیرند.

**Comment by rsharifnasab** [comment]
سلام
کاملا حق با شماست ولی مشکل نمایش متون فارسی در readme هست
مثل همین جمله بالا که به هم ریخت.

**Comment by farooqkz** [comment]
درسته
شاید گیت‌هاب مکان مناسبی برای فارسی نباشه.

**Comment by farooqkz** [comment]
<div dir="rtl">
البته این جوری هم میشه مثلا an English کلمه اینجا :))
</div>
@rsharifnasab
