### ISSUE TITLE
Try CherryPy too!

### ISSUE THREAD

**Issue by farooqkz** [rsharifnasab/my-learning#3]

**Comment by rsharifnasab** [comment]
سلام!
بله امتحان کردم، اتفاقا به نظرم جذاب اومد 
ولی ترجیح می‌دهم چیزی  یاد بگیرم که اسمش به گوش آدم‌های بیشتری خورده باشد حداقل
بازار کار بماند، چون علاقه‌ای به بک‌اند نداشتم
